export const BADGE_MAP: Record<string, string> = {
  'FC Seoul':                'K09',
  'Ulsan HD FC':             'K01',
  'Ulsan HD':                'K01',
  'Ulsan Hyundai FC':        'K01',
  'Jeonbuk Hyundai Motors':  'K05',
  'Jeju United':             'K04',
  'Jeju SK':                 'K04',
  'Jeju United FC':          'K04',
  'Pohang Steelers':         'K03',
  'Incheon United':          'K18',
  'Incheon United FC':       'K18',
  'Gimcheon Sangmu FC':      'K35',
  'Gimcheon Sangmu':         'K35',
  'Sangju Sangmu':           'K35',
  'Gwangju FC':              'K22',
  'Gangwon FC':              'K21',
  'Daejeon Citizen':         'K10',
  'Daejeon Hana Citizen':    'K10',
  'Daegu FC':                'K17',
  'Suwon FC':                'K29',
  'Suwon Samsung Bluewings': 'K02',
  'Bucheon FC 1995':         'K26',
  'Seongnam FC':             'K08',
  'Chungnam Asan FC':        'K34',
  'Chungnam Asan':           'K34',
  'Jeonnam Dragons':         'K07',
  'Busan IPark':             'K06',
  'Ansan Greeners':          'K32',
  'Gyeongnam FC':            'K20',
  'FC Anyang':               'K27',
  'Anyang':                  'K27',
  'Seoul E-Land FC':         'K31',
  'Seoul E-Land':            'K31',
  'Chungbuk Cheongju FC':    'K37',
  'Chungbuk Cheongju':       'K37',
  'Gimpo FC':                'K36',
  'Gimpo Citizen':           'K36',
  'Gimhae FC':               'K41',
  'Hwaseong FC':             'K39',
  'Yongin FC':               'K42',
  'Paju Frontier':           'K40',
  'Cheonan City':            'K38',
};

export function getBadgeUrl(teamName: string, supabaseUrl: string): string | null {
  const kcode = BADGE_MAP[teamName];
  if (!kcode) return null;
  return `${supabaseUrl}/storage/v1/object/public/team-badges/${kcode}.png`;
}
